license_id: "cc-by-igo"
notes: "This dataset is UCDP's most disaggregated dataset, covering individual events of organized violence (phenomena of lethal violence occurring at a given time and place). These events are sufficiently fine-grained to be geo-coded down to the level of individual villages, with temporal durations disaggregated to single, individual days.

Sundberg, Ralph, and Erik Melander, 2013, “Introducing the UCDP Georeferenced Event Dataset”, Journal of Peace Research, vol.50, no.4, 523-532

Högbladh Stina, 2019, “UCDP GED Codebook version 19.1”, Department of Peace and Conflict Research, Uppsala University"
caveats: ""
methodology: "Other"
methodology_other: "[UCDP's Methodology page](https://www.pcr.uu.se/research/ucdp/methodology/) contains information about how UCDP collects, evaluates, codes and validates event data."
dataset_source: "Uppsala Conflict Data Program"
package_creator: "mcarans"
private: False  # has to be True or False
url: ~
state: "active"  # always "active".
